name: develop
root: ~/projects/Project_Tree/repos/develop/
windows:
  - editor: nvim .
  - claude: claude
  - server:
      layout: even-horizontal
      panes:
        - yarn run expo start
        - # secondary pane
  - terminal:
